apiVersion: v2
name: starship
description: >
  "Helm Charts for Starship, Tricorder Observability's next-generatoin "
  "Observability Platform built on eBPF+WASM"

sources:
  - https://github.com/tricorder-observability/Starship/helm-charts

maintainers:
  - name: yaxiong-zhao

# Chart version, updating this version requires a release.
version: v0.0.49

# starship image tag
appVersion: v0.0.49

dependencies:
  - name: timescaledb-single
    version: 0.27.5
    repository: "https://charts.timescale.com"
    condition: timescaledb-single.enabled
  - name: promscale
    version: 14.6.1
    repository: "https://charts.timescale.com"
    condition: promscale.enabled
  - name: kube-prometheus-stack
    version: 43.2.1
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kube-prometheus-stack.enabled
  - name: grafana
    version: "6.51.1"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
